# Site settings
title: Wode "Nimo" Ni
description: "In the ocean of code, I swim."
url: "http://wodeni.github.io"
baseurl: ""
google_analytics: "UA-112343565-2"
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Wode "Nimo" Ni'
  email: wn2155@columbia.edu
  twitter_username: wodenimoni
  github_username: wodeni
  linkedin_username: wode-ni

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 10
paginate_path: "/blog/:title"
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-font-awesome-sass
